### ISSUE TITLE
BC Problems with Actor Crititc (PPO) getting action probabilities 

### ISSUE THREAD

**Issue by benspoek** [Stable-Baselines-Team/rl-colab-notebooks#8]
I am implementing the Stable Baselines3 - Pretraining with Behavior Cloning example for a PPO agent with a discrete action space. However I can not retrieve the logits by the method proposed in the code

latent_pi, _, _ = model._get_latent(data)
                  logits = model.action_net(latent_pi)
                  action_prediction = logits

due to a AttributeError: 'ActorCriticPolicy' object has no attribute '_get_latent'. How can i work around that? is there another possibility to get the action probabilities?

**Comment by araffin** [comment]
Hello,
the PPO code was updated but not the BC one apparently...
PPO policy now has a `get_distribution()` method from which you should be able to extract logits ;)
see https://github.com/DLR-RM/stable-baselines3/blob/52c29dc497fa2eb235d0476b067bed8ac488fe64/stable_baselines3/common/policies.py#L650

A PR that solves this issue is welcomed ;)
